name: Continuous Integration
on: [push, pull_request]

jobs:
  lint:
    name: Check lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install --frozen-lockfile
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: lint
  prettier:
    name: Check prettier
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install --frozen-lockfile
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: prettier
  test:
    name: Run tests
    runs-on: ubuntu-latest
    env:
      TRANSLATION_SERVICE_URL: http://localhost:8080/cql/translator
      INPUT_CQL: ./cql
      OUTPUT_ELM: ./output-elm
      VALUESETS: ./valuesets
      PATIENTS: ./test/fixtures/patients
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install --frozen-lockfile
      - run: chmod +x ./testing-harness/scripts/run_tests.sh
      - run: yarn test
      # Defining a new ENV variable set for our testing-harness tests
      - name: 'testing-harness tests'
        env:
          INPUT_CQL: ./testing-harness/test/fixtures/cql
          OUTPUT_ELM: ./testing-harness/test/fixtures/elm
          VALUESETS: ./testing-harness/test/fixtures/valuesets
          PATIENTS: ./testing-harness/test/fixtures/patients
        run: yarn test:testing-harness
